"""High-level public API for AgencityLab."""

from .version import __version__
from .models import (
    AgencityResult,
    ExperimentMetadata,
    ObservableAgencityFieldResult,
    DynamicalAgencityFieldState,
    DynamicalAgencityFieldSolution,
    FieldModelMetadata,
    ParameterProvenance,
    ParameterSource,
    RESULT_SCHEMA_VERSION,
)
from .scientific_status import ScientificStatus
from .exceptions import (
    AgencityError,
    AgencityValidationError,
    PhysicalParameterError,
    UnitValidationError,
    BatchItemError,
    StreamStateError,
    StreamNotReadyError,
)
from .analysis import ANALYSIS_SCHEMA_VERSION, RegimeCriteria
from .api.compute import compute_agencity
from .fields import (
    compute_agencity_field,
    beta_to_phi,
    phi_from_observable_field,
    QuarticAgencityPotential,
    vacuum_amplitude,
    vacuum_state,
    field_energy_density,
    UniformRectilinearGrid,
    PeriodicBoundary,
    DirichletBoundary,
    NeumannBoundary,
    gradient,
    laplacian,
    klein_gordon_acceleration,
    dissipative_klein_gordon_acceleration,
    tdgl_rhs,
    simulate_klein_gordon,
    simulate_dissipative_klein_gordon,
    simulate_tdgl,
    domain_wall_profile,
    domain_wall_residual,
    vortex_field,
    vortex_radial_residual,
    phase_winding,
    field_zero_mask,
)
from .thermodynamics import (
    PhaseLawFit,
    contrast_agencial_entropy,
    dissipation_density,
    energy_balance_residual,
    entropy_production_density,
    field_agencial_entropy,
    landauer_agencity_power,
    landauer_characteristic_power,
    modulus_law_margin,
    modulus_law_satisfied,
    phase_law_prediction,
    phase_law_residual,
    second_law_residual,
    structural_information_rate,
    temperature_dependent_lambda,
    thermal_reference_phase_fit,
)
from .gravity import (
    GRAVITY_METRIC_SIGNATURE,
    conformal_coupling,
    covariant_scalar_derivative,
    curved_field_residual,
    einstein_equation_residual,
    matter_lagrangian_density,
    minimal_coupling,
    minkowski_inverse_metric,
    minkowski_metric,
    nonminimal_coupling_density,
    stress_energy_tensor,
)
from .quantum import (
    agencity_uncertainty_lower_bound,
    annihilation_operator,
    one_loop_quartic_beta,
    radial_angular_frequency,
    radial_mass_squared,
)
from .applications.cosmology import (
    FlatFLRWSolution,
    friedmann_constraint_residual,
    homogeneous_energy_density,
    homogeneous_pressure,
    simulate_flat_flrw,
)
from .api.extensions import (
    RIEMANNIAN_EXTENSION_STATUS,
    compute_agencity_spectrum,
    compute_discrete_agencity,
    compute_multivariate_agencity,
    optimize_agencity_window,
    riemannian_extension_status,
)
from .api.analyze import (
    analyze_agencity,
    textual_analysis,
    analyze_regime,
    analyze_regime_signature,
    analyze_coherence,
    analyze_geometry,
    analyze_stability,
    analyze_information,
    analyze_events,
    analyze_transitions,
    analyze_multiscale,
    analyze_signature,
)
from .api.pipeline_api import AgencityPipeline, pipeline
from .api.streaming import AgencityStream, stream_agencity
from .api.batch import run_batch, analyze_batch, summarize_batch, compare_batch
from .api.report import build_report, build_text_report, summarize
from .api.export import (
    SCIENTIFIC_UX_SCHEMA_VERSION,
    export_json,
    export_csv,
    export_result_csv,
    export_study_json,
    export_excel,
    export_pdf,
    export_report,
)
from .api.visualize import visualize_agencity, visualize_multiscale_spectrum
from .api.scientific import ScientificStudy, scientific_workflow
from .api.shortcuts import run, inspect, plot, summarize as quick_summary
from .backends.selector import available_backends, backend_capabilities, get_backend

PipelineBuilder = AgencityPipeline
pipeline_builder = pipeline

__all__ = [
    "__version__",
    "RESULT_SCHEMA_VERSION",
    "ANALYSIS_SCHEMA_VERSION",
    "SCIENTIFIC_UX_SCHEMA_VERSION",
    "ScientificStatus",
    "RegimeCriteria",
    "AgencityResult",
    "ObservableAgencityFieldResult",
    "DynamicalAgencityFieldState",
    "DynamicalAgencityFieldSolution",
    "FieldModelMetadata",
    "ParameterProvenance",
    "ParameterSource",
    "ExperimentMetadata",
    "ScientificStudy",
    "AgencityError",
    "AgencityValidationError",
    "PhysicalParameterError",
    "UnitValidationError",
    "BatchItemError",
    "StreamStateError",
    "StreamNotReadyError",
    "compute_agencity",
    "compute_agencity_field",
    "beta_to_phi",
    "phi_from_observable_field",
    "QuarticAgencityPotential",
    "vacuum_amplitude",
    "vacuum_state",
    "field_energy_density",
    "UniformRectilinearGrid",
    "PeriodicBoundary",
    "DirichletBoundary",
    "NeumannBoundary",
    "gradient",
    "laplacian",
    "klein_gordon_acceleration",
    "dissipative_klein_gordon_acceleration",
    "tdgl_rhs",
    "simulate_klein_gordon",
    "simulate_dissipative_klein_gordon",
    "simulate_tdgl",
    "domain_wall_profile",
    "domain_wall_residual",
    "vortex_field",
    "vortex_radial_residual",
    "phase_winding",
    "field_zero_mask",
    "PhaseLawFit",
    "contrast_agencial_entropy",
    "dissipation_density",
    "energy_balance_residual",
    "entropy_production_density",
    "field_agencial_entropy",
    "landauer_agencity_power",
    "landauer_characteristic_power",
    "modulus_law_margin",
    "modulus_law_satisfied",
    "phase_law_prediction",
    "phase_law_residual",
    "second_law_residual",
    "structural_information_rate",
    "temperature_dependent_lambda",
    "thermal_reference_phase_fit",
    "GRAVITY_METRIC_SIGNATURE",
    "conformal_coupling",
    "covariant_scalar_derivative",
    "curved_field_residual",
    "einstein_equation_residual",
    "matter_lagrangian_density",
    "minimal_coupling",
    "minkowski_inverse_metric",
    "minkowski_metric",
    "nonminimal_coupling_density",
    "stress_energy_tensor",
    "agencity_uncertainty_lower_bound",
    "annihilation_operator",
    "one_loop_quartic_beta",
    "radial_angular_frequency",
    "radial_mass_squared",
    "FlatFLRWSolution",
    "friedmann_constraint_residual",
    "homogeneous_energy_density",
    "homogeneous_pressure",
    "simulate_flat_flrw",
    "compute_agencity_spectrum",
    "optimize_agencity_window",
    "compute_discrete_agencity",
    "compute_multivariate_agencity",
    "riemannian_extension_status",
    "RIEMANNIAN_EXTENSION_STATUS",
    "analyze_agencity",
    "textual_analysis",
    "analyze_regime",
    "analyze_regime_signature",
    "analyze_coherence",
    "analyze_geometry",
    "analyze_stability",
    "analyze_information",
    "analyze_events",
    "analyze_transitions",
    "analyze_multiscale",
    "analyze_signature",
    "scientific_workflow",
    "pipeline",
    "AgencityPipeline",
    "PipelineBuilder",
    "pipeline_builder",
    "AgencityStream",
    "stream_agencity",
    "run_batch",
    "analyze_batch",
    "summarize_batch",
    "compare_batch",
    "build_report",
    "build_text_report",
    "summarize",
    "export_json",
    "export_csv",
    "export_result_csv",
    "export_study_json",
    "export_excel",
    "export_pdf",
    "export_report",
    "visualize_agencity",
    "visualize_multiscale_spectrum",
    "run",
    "inspect",
    "plot",
    "quick_summary",
    "get_backend",
    "available_backends",
    "backend_capabilities",
]
