"""
Analysis layer for AgencityLab.

This layer interprets complex agencity outputs:
    - regimes
    - stability
    - diagnostics
    - information theory
    - geometry
    - coherence
    - complexity
    - correlations
    - anomalies
    - multiscale behavior
    - scientific reports

Unlike the core layer, analysis modules provide:
    - scientific interpretation,
    - diagnostics,
    - classification,
    - descriptive summaries,
    - advanced observables.

IMPORTANT
---------
The analysis layer does NOT redefine
canonical equations.

It operates on outputs generated by:
    agencitylab.core

Main theoretical dimensions
---------------------------
    - dynamic intensity
    - structural intensity
    - orientation coherence
    - information structure
    - agencity persistence
    - multiscale organization
    - real-agencity diagnostics

Canonical references
--------------------
Volume 1:
    - Dynamic / structural intensity
    - Contrast J
    - Agencity beta

Volume 2:
    - Structural orientation Θ
    - Angular variance Σ_Θ
    - Real-agencity criterion
"""

# ============================================================
# METRICS
# ============================================================

from .metrics import (
    agencity_components,
    agencity_mean,
    agencity_variance,
    agencity_peak,
    agencity_integral,
    agencity_energy,
    agencity_power_mean,
    agencity_efficiency,
    global_efficiency,
)

# ============================================================
# REGIMES & STABILITY
# ============================================================

from .regimes import (
    classify_regime,
    detect_regime_changes,
)

from .stability import (
    stability_summary,
)

# ============================================================
# INFORMATION THEORY
# ============================================================

from .information import (

    # Shannon information
    shannon_entropy,
    conditional_entropy,

    # Agencity information
    agencity_information_index,
    agencity_information_density,
    agencity_structural_information,
    agencity_phase_information,
    full_information_summary,

    # Physics
    landauer_lower_bound,
)

# ============================================================
# EVENTS & TRANSITIONS
# ============================================================

from .events import (
    detect_events,
    event_summary,
)

from .transitions import (
    detect_transitions,
    transition_summary,
)

# ============================================================
# DIAGNOSTICS
# ============================================================

from .diagnostics import (
    compute_energy,
    compute_derivative,
    rolling_variance,
    summarize_diagnostics,
)

# ============================================================
# GEOMETRY & CORRELATION
# ============================================================

from .geometry import (
    geometric_summary,
)

from .correlation import (
    full_correlation_summary,
)

# ============================================================
# COHERENCE
# ============================================================

from .coherence import (

    # global coherence
    full_coherence,
    full_structural_coherence,

    # phase coherence
    phase_coherence,

    # amplitude / temporal
    amplitude_coherence,
    temporal_coherence,

    # orientation structure
    orientation_statistics,
    angular_stability,

    # canonical criterion
    real_agencity_criterion,
)

# ============================================================
# COMPLEXITY & ANOMALIES
# ============================================================

from .complexity import (
    complexity_summary,
)

from .anomalies import (
    anomaly_summary,
)

# ============================================================
# MULTISCALE
# ============================================================

from .multi_scale import (
    agencity_multiscale,
    agencity_spectrum_array,
    find_optimal_tau,
)

# ============================================================
# SIGNATURE
# ============================================================

from .signature import (
    agencity_signature,
)

# ============================================================
# REPORTS
# ============================================================

from .reports import (
    build_report_dict,
    build_text_report,
)

# ============================================================
# PUBLIC API
# ============================================================

__all__ = [

    # ========================================================
    # metrics
    # ========================================================

    "agencity_components",
    "agencity_mean",
    "agencity_variance",
    "agencity_peak",
    "agencity_integral",
    "agencity_energy",
    "agencity_power_mean",
    "agencity_efficiency",
    "global_efficiency",

    # ========================================================
    # regimes
    # ========================================================

    "classify_regime",
    "detect_regime_changes",

    # ========================================================
    # stability
    # ========================================================

    "stability_summary",

    # ========================================================
    # information theory
    # ========================================================

    "shannon_entropy",
    "conditional_entropy",

    "agencity_information_index",
    "agencity_information_density",
    "agencity_structural_information",
    "agencity_phase_information",

    "full_information_summary",

    "landauer_lower_bound",

    # ========================================================
    # events & transitions
    # ========================================================

    "detect_events",
    "event_summary",

    "detect_transitions",
    "transition_summary",

    # ========================================================
    # diagnostics
    # ========================================================

    "compute_energy",
    "compute_derivative",
    "rolling_variance",
    "summarize_diagnostics",

    # ========================================================
    # geometry & correlation
    # ========================================================

    "geometric_summary",
    "full_correlation_summary",

    # ========================================================
    # coherence
    # ========================================================

    "full_coherence",
    "full_structural_coherence",

    "phase_coherence",
    "amplitude_coherence",
    "temporal_coherence",

    "orientation_statistics",
    "angular_stability",

    "real_agencity_criterion",

    # ========================================================
    # complexity & anomalies
    # ========================================================

    "complexity_summary",
    "anomaly_summary",

    # ========================================================
    # multiscale
    # ========================================================

    "agencity_multiscale",
    "agencity_spectrum_array",
    "find_optimal_tau",

    # ========================================================
    # signature
    # ========================================================

    "agencity_signature",

    # ========================================================
    # reports
    # ========================================================

    "build_report_dict",
    "build_text_report",
]